### ISSUE TITLE
RegisterInstrumentation can not set in file

### ISSUE THREAD

**Issue by daixiang0** [weaveworks/common#156]
`RegisterInstrumentation` option can not be changed in yaml, refer to https://github.com/weaveworks/common/blob/master/server/server.go#L33.

But in https://github.com/weaveworks/common/blob/master/server/server.go#L158-L160, still do check.

Better to expose this setting to yaml setting.

**Comment by bboreham** [comment]
The setting can be changed from the command-line, right?

**Comment by daixiang0** [comment]
But not with file, change the title.
