### ISSUE TITLE
error of "github.com/uber/jaeger-lib/metrics/testutils"

### ISSUE THREAD

**Issue by Francis-007** [weaveworks/common#197]
gitlab.com/momentum-valley/rome/cmd/rome imports
        github.com/weaveworks/common/middleware imports
        github.com/uber/jaeger-client-go tested by
        github.com/uber/jaeger-client-go.test imports
        github.com/uber/jaeger-lib/metrics/testutils: module github.com/uber/jaeger-lib@latest found (v2.2.0+incompatible), but does not contain package github.com/uber/jaeger-lib/metrics/testutils

**Comment by bboreham** [comment]
I don't know what went wrong for you, but it's working fine in CI and `go mod tidy` makes no changes so I'm going to close this as something unique to your environment.
