### ISSUE TITLE
common logging has type error

### ISSUE THREAD

**Issue by pinglinvip** [weaveworks/common#94]
D:\...\github.com\weaveworks\common\logging\logging.go:35:13: cannot use hook (type *promrus.PrometheusHook) as type "github.com/sirupsen/logrus".Hook in argument to "github.com/sirupsen/logrus".AddHook:

	*promrus.PrometheusHook does not implement "github.com/sirupsen/logrus".Hook (wrong type for Fire method)

		have Fire(*"github.com/weaveworks/promrus/vendor/github.com/sirupsen/logrus".Entry) error
		want Fire(*"github.com/sirupsen/logrus".Entry) error

**Comment by pinglinvip** [comment]
that is my mistake, I hope I'm not disturbing you

**Comment by olesiapoz** [comment]
how did you fixed
